import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/components/themeProvider";
import Footer from "@/components/components/footer";
import ResizableNavbar from "@/components/components/resizableNavbar";
import FloatingActionButton from "@/components/components/floatingActionButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange>
          <div className="flex flex-col min-h-screen">
            <ResizableNavbar/>
            <div className="flex-grow container mx-auto">
              {children}
            </div>
            <FloatingActionButton />
            <Footer/>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
